### ISSUE TITLE
deconPeaker.py does not work

### ISSUE THREAD

**Issue by jingyu0602** [lihuamei/DeconPeaker#1]
Hi Huamei,

I'm trying to predict cell proportions with your tools for ATAC-seq data and it does not work even I'm running the example data. 
The command with issue is "deconPeaker.py deconvolution --lib-strategy=ATAC-Seq --mixture=test\examples\ATAC-Seq\GSE74912_Corces_MR_synthetic_mixture_counts_data.xls --pure=test\examples\ATAC-Seq\GSE74912_Corces_MR_pure_readcounts_signature_matrix.xls --format=TABLE --pvalue=FALSE --outdir=results\GSE74912_Corces_MR". 
It does not generate a result folder and results, it finishes quickly and seems like not running but no error is shown. Is there something I did wrong or issues with the script? Look forward to your reply

Jingyu

**Comment by lihuamei** [comment]
Dear Jingyu,
        I will check the bugs and get back to you as soon as they are fixed.
greetings,
Huamei Li













At 2021-07-15 13:45:40, "jingyu0602" ***@***.***> wrote:

Hi Huamei,

I'm trying to predict cell proportions with your tools for ATAC-seq data and it does not work even I'm running the example data.
The command with issue is "deconPeaker.py deconvolution --lib-strategy=ATAC-Seq --mixture=test\examples\ATAC-Seq\GSE74912_Corces_MR_synthetic_mixture_counts_data.xls --pure=test\examples\ATAC-Seq\GSE74912_Corces_MR_pure_readcounts_signature_matrix.xls --format=TABLE --pvalue=FALSE --outdir=results\GSE74912_Corces_MR".
It does not generate a result folder and results, it finishes quickly and seems like not running but no error is shown. Is there something I did wrong or issues with the script? Look forward to your reply

Jingyu

**Comment by jingyu0602** [comment]
Great! Thanks for your reply!

**Comment by lihuamei** [comment]
Hi, jingyu! I have refactored the code and updated the python version to 3. Since DeconPeaker will call R, please make sure that all the dependency packages are installed correctly. If you have any questions, please feel free to contact me.
















在 2021-07-15 14:22:55，"jingyu0602" ***@***.***> 写道：

Great! Thanks for your reply!

**Comment by jingyu0602** [comment]
Hi Huamei,

Thanks for fixing bugs! I'm trying the example data, should I type something after (Pdb) to run? I'm not sure what to input here. Look forward to your reply. 
<img width="1440" alt="截屏2021-07-17 上午10 28 36" src="https://user-images.githubusercontent.com/75610844/126022655-e3ee3e6d-ce99-4810-b1c0-b24896485b81.png">

Jingyu

**Comment by lihuamei** [comment]
Hi Jingyu, I have deleted the pdb debug line, please clone DeconPeaker again.

**Comment by jingyu0602** [comment]
Hi Huamei, thanks for fixing this bug and it runs!

Cheers

**Comment by jingyu0602** [comment]
Hi Huamei,

Maybe true_VS_est_scatter_plot.py also has issues? or something I did wrong? 
The error is shown below:
  File "./test/true_VS_est_scatter_plot.py", line 32
    if len(sys.argv[1 : ]) <> 3:
                            ^
SyntaxError: invalid syntax

Look forward to your reply
Jingyu

**Comment by lihuamei** [comment]
> Hi Huamei,
> 
> Maybe true_VS_est_scatter_plot.py also has issues? or something I did wrong?
> The error is shown below:
> File "./test/true_VS_est_scatter_plot.py", line 32
> if len(sys.argv[1 : ]) <> 3:
> ^
> SyntaxError: invalid syntax
> 
> Look forward to your reply
> Jingyu

Hi, Jingyu, this is an error caused by the python version, I have fixed it, please re-run it.

**Comment by jingyu0602** [comment]
Hi Huamei,

Thanks for all you did. But it still failed when I tried running example data to plot. Is it issue of myself or the code?
<img width="1438" alt="截屏2021-07-17 下午5 38 43" src="https://user-images.githubusercontent.com/75610844/126032905-e8bcd39b-68a0-4c27-949f-bc2e46309d3b.png">

Jingyu

**Comment by lihuamei** [comment]
> Hi Huamei,
> 
> Thanks for all you did. But it still failed when I tried running example data to plot. Is it issue of myself or the code?
> <img alt="截屏2021-07-17 下午5 38 43" width="1438" src="https://user-images.githubusercontent.com/75610844/126032905-e8bcd39b-68a0-4c27-949f-bc2e46309d3b.png">
> 
> Jingyu

Hi Yu Jing, just warning messages, not errors. I have reset the warning level and can re-clone it.

**Comment by jingyu0602** [comment]
Hi Huamei, it works smoothly. Thanks for all you done. Cheers
